version: '3.11'

services:

  web:
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - "50800:8000"
      - "4666:4444"
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true

  db:
    image: postgres:13.0-alpine
    ports:
      - "30333:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .envs/.local/.postgres

  celery:
      build:
        context: .
        dockerfile: compose/local/django/Dockerfile
      hostname: worker
      command: celery --app=config worker --loglevel=info
      volumes:
        - ./:/usr/src/app
      env_file:
        - ./.envs/.local/.django
      links:
        - redis
      depends_on:
        - web
        - redis

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

volumes:
  postgres_data: {}
