# Generated by Django 4.1.7 on 2023-03-15 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
