# Generated by Django 4.1.7 on 2023-03-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_pickpoint_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
