# Generated by Django 4.1.7 on 2023-03-19 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_address_is_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickpoint',
            name='customer',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
