# Generated by Django 4.1.7 on 2023-03-19 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_pickpoint_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.address'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_pickpoint',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.pickpoint'),
        ),
    ]
