# Generated by Django 4.1.7 on 2023-03-20 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_pickpoint',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pickpoint',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.address'),
        ),
    ]
