# Generated by Django 4.1.7 on 2023-03-20 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_address_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='owner',
        ),
        migrations.AddField(
            model_name='address',
            name='owner',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
