# Generated by Django 4.1.7 on 2023-03-20 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_remove_address_owner_address_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickpoint',
            name='customer',
        ),
    ]
