# Generated by Django 4.1.7 on 2023-03-22 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_pickpoint',
        ),
        migrations.DeleteModel(
            name='PickPoint',
        ),
    ]
