# Generated by Django 4.1.7 on 2023-03-10 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
    ]
