# Generated by Django 4.1.7 on 2023-03-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_order_options_rename_order_date_order_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
