# Generated by Django 4.1.7 on 2023-03-11 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_customer_user_alter_product_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
