# Generated by Django 4.1.7 on 2023-03-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
