# Generated by Django 4.1.7 on 2023-03-20 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
    ]
