# Generated by Django 4.1.7 on 2023-03-20 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_user_first_name_alter_user_last_name'),
        ('orders', '0008_remove_order_city_remove_order_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.address'),
        ),
    ]
