# Generated by Django 4.1.7 on 2023-03-20 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_user_first_name_alter_user_last_name'),
        ('orders', '0009_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickpoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.pickpoint'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.address'),
        ),
    ]
